### PR TITLE
Custom SponsorBlock setting

### PR DESCRIPTION
**Pull request by patgruber**
This adds a setting to change the SponsorBlock api url to the user settings menu as described in: https://github.com/ViewTube/viewtube/issues/1520

### CODE REVIEW

**Comment by patgruber** [comment]
I'm think the CSP might need to be updated in `main.ts` . But have to check behind a https proxy later

**Comment by moisout** [comment]
Very cool, thanks!

**Comment by moisout** [comment]
~~Can you add the setting to the backend too? So it gets synced with the accounts settings.
Like this: https://github.com/ViewTube/viewtube/pull/2795/files#diff-9c6207724ba0bc59515b00a1b94f45b4cc2c7553036240dfb4c62640f439dedb~~

**Comment by moisout** [comment]
I have implemented a proxy for sponsorblock, I'll merge this and combine the two. New Release coming soon!

**Comment by patgruber** [comment]
Sounds good!

**Pull request merged**
