### PR TITLE
Issue 2450 search enhancement

### PR DESCRIPTION
**Pull request by frozenduck**
This PR adds automatic search execution when you click on an item in the search drop-down list. 

https://github.com/ViewTube/viewtube/issues/2450

### CODE REVIEW

**Comment by moisout** [comment]
Thanks a lot for this PR, I'll check it out as soon as i can!

**Comment by moisout** [comment]
Awesome, LGTM

**Comment by frozenduck** [comment]
Thank you, the next task I'd like to work on is
https://github.com/ViewTube/viewtube/issues/2152

I'll probably have time at the end of the week.
I would like to know if you have any progress on this issue now ? So that our code doesn't overlap.

**Comment by moisout** [comment]
> Thank you, the next task I'd like to work on is #2152
> 
> I'll probably have time at the end of the week. I would like to know if you have any progress on this issue now ? So that our code doesn't overlap.

I haven't started working on that, feel free to!
I am currently working on:
- Replacing the comments API (It's why the tests are failing)
- The new Video Player

**Pull request merged**
