### PR TITLE
Reduce screenshots' file sizes in README.md

### PR DESCRIPTION
**Pull request by Mennaruuk**
PR reduces the file size of the three screenshots by as much as 90% to ensure faster loading. Super minor update!

### CODE REVIEW

**Comment by mauriceoegerli** [comment]
This is a good addition, thank you! Could you also delete the original images?

**Comment by Mennaruuk** [comment]
I replaced the links to the original images with the new links. Is that what you’re asking?

**Comment by mauriceoegerli** [comment]
The original images were in the folder .github/images/screenshots

**Comment by mauriceoegerli** [comment]
Nice, thank you

**Comment by moisout** [comment]
@all-contributors please add @Mennaruuk for doc

**Pull request merged**
